[package]
name = "sequencer"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Starknet
# TODO: remove the blockifier patch on the workspace once we can remove Katana.
blockifier = { package = "blockifier", git = "https://github.com/starkware-libs/blockifier.git", tag = "v0.3.0-rc0" }
starknet_api = { workspace = true }
starknet = { workspace = true }

# Other
tracing = { workspace = true }
rustc-hash = "1.1.0"

[dev-dependencies]
lazy_static = { workspace = true }
serde_json = { workspace = true }
